---
- hosts: prod
  become: true
  gather_facts: false
  tasks:
    - cron:
        name: restart rsyslog
        minute: "0"
        hour: "6,23"
        job: "systemctl restart rsyslog"

- hosts: webservers
  become: true
  gather_facts: false
  tasks:
    - cron:
        name: restart rsyslog
        minute: "0"
        hour: "2"
        weekday: "1"
        job: "systemctl restart rsyslog"
...
