---
- hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: iterate over the hosts on the play
      debug:
        msg: >
          {# using jinja2 for statement to iterate over hosts from the play -#}
          {% for mnode in webservers.group -%}
            Host: {{ hostvars[mnode]['inventory_hostname'] }}
          {% endfor -%}
...
