---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create the /root/mark_file file on all managed nodes
      file:
        name: /root/mark_file
        state: touch
        owner: mark
        group: mark
        mode: "2750"
...
